id: P004181
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:58:49.347237
source_metadata:
  id: bdr:W2046
  title: གསུང་འབུམ། དཔལ་ལྡན་ཡེ་ཤེས།
  author: ''
  volumes:
    4955b7fdcbd048039283d85eb2b4921a:
      image_group_id: I2216
      title: ''
      volume_number: 1
      total_pages: 552
    4bac65133c0f44e797fa52e586ef1ec2:
      image_group_id: I2217
      title: ''
      volume_number: 2
      total_pages: 558
    973979748c744e10ac0c960ee4ee6de8:
      image_group_id: I2218
      title: ''
      volume_number: 3
      total_pages: 808
    8b825c9b67c54359a45d9901a4f5ebb8:
      image_group_id: I2219
      title: ''
      volume_number: 4
      total_pages: 508
    903ff9c458ea42ff9f55aecf61f5a009:
      image_group_id: I2220
      title: ''
      volume_number: 5
      total_pages: 596
    22be00c46b6441b6a4604996f30b6be9:
      image_group_id: I2221
      title: ''
      volume_number: 6
      total_pages: 554
    74bd97541bb04d898ab59a3b36f79cb1:
      image_group_id: I2222
      title: ''
      volume_number: 7
      total_pages: 558
    a2b730311c1c4c2f88406954c1ea40d2:
      image_group_id: I2223
      title: ''
      volume_number: 8
      total_pages: 574
    4ed8edbc9bd14144955e3d4ef2a145bc:
      image_group_id: I2224
      title: ''
      volume_number: 9
      total_pages: 544
    364469d5dc0c46f3beb4a423816d1aa0:
      image_group_id: I2225
      title: ''
      volume_number: 10
      total_pages: 496
    91814df2656c458ebd2f1900dbdc0cc3:
      image_group_id: I2226
      title: ''
      volume_number: 11
      total_pages: 764
    5ca186e29d1a477ab125d4e18d7cf26d:
      image_group_id: I2227
      title: ''
      volume_number: 12
      total_pages: 620
    0309293ec7bd4280b6e70c01bad1014f:
      image_group_id: I2228
      title: ''
      volume_number: 13
      total_pages: 608
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
