id: I933515F3
legacy_id: P004181
ocr_import_info:
  bdrc_scan_id: W2046
  source: bdrc
  ocr_info:
    timestamp: '2021-01-28T09:59:14'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T13:27:47.576508+00:00'
last_modified: 2022-09-01 21:29:04.420439
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2046
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW2046
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། དཔལ་ལྡན་ཡེ་ཤེས།
  author: དཔལ་ལྡན་ཡེ་ཤེས།
statistics:
  ocr_word_mean_confidence_index: 0.6782604238771993
  ocr_word_median_confidence_index: 0.7300000190734863
quality: null
bases:
  I2224:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2224
      total_pages: 544
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I2224.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9805369209123138
    legacy_id: v009
  I2217:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2217
      total_pages: 558
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2217.txt
    legacy_id: v002
  I2218:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2218
      total_pages: 808
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2218.txt
    statistics:
      ocr_word_median_confidence_index: 0.6299999952316284
      ocr_word_mean_confidence_index: 0.5755932225640548
    legacy_id: v003
  I2222:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2222
      total_pages: 558
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I2222.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.8748548868404686
    legacy_id: v007
  I2216:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2216
      total_pages: 552
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2216.txt
    statistics:
      ocr_word_median_confidence_index: 0.92
      ocr_word_mean_confidence_index: 0.8527135678391959
    legacy_id: v001
  I2226:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2226
      total_pages: 764
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I2226.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.7491992616425581
    legacy_id: v011
  I2221:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2221
      total_pages: 554
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I2221.txt
    legacy_id: v006
  I2219:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2219
      total_pages: 508
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I2219.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.6027394212732602
    legacy_id: v004
  I2227:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2227
      total_pages: 620
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I2227.txt
    statistics:
      ocr_word_median_confidence_index: 0.6899999976158142
      ocr_word_mean_confidence_index: 0.6599830941305773
    legacy_id: v012
  I2225:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2225
      total_pages: 496
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I2225.txt
    legacy_id: v010
  I2223:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2223
      total_pages: 574
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I2223.txt
    statistics:
      ocr_word_median_confidence_index: 0.6299999952316284
      ocr_word_mean_confidence_index: 0.6092881263437334
    legacy_id: v008
  I2220:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2220
      total_pages: 596
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I2220.txt
    legacy_id: v005
  I2228:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2228
      total_pages: 608
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I2228.txt
    statistics:
      ocr_word_median_confidence_index: 0.7300000190734863
      ocr_word_mean_confidence_index: 0.6468408561517394
    legacy_id: v013
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
